### ISSUE TITLE
Вера в то что нил не прилетит

### ISSUE THREAD

**Issue by nextel** [lzakharov/hlcup2017#7]
https://github.com/lzakharov/hlcup2017/blob/3be12c6349922ea01f146a02a12f8e8577bf034f/models/user.go#L16

простые типы как указатели? в твеом случае в этом нет никакого смысла)

**Comment by lzakharov** [comment]
@nextel когда приходит запрос на обновление я так проверяю какие поля были указаны, а какие нет:) Для строк наверное просто `omitempty` надо было добавить, но с примитивами по другому хз как жить.

**Comment by lzakharov** [comment]
@nextel когда приходит запрос на обновление я так проверяю какие поля были указаны, а какие нет:) Это как-то можно по другому обработать?
